afterWe/Run_Base_front-end

src/pages/Login/Login.style.ts, src/pages/Login/Login.tsx
🚀 Ticket
name : 로그인
task : 로그인 레이아웃
🐝 Issue
회원가입과 스타일을 통일해야하니 나중에 추가작업이 필요함
=> ADD: Login 레이아웃 구성

src/Router.tsx, src/layout/component/AddressEdit.style.ts, src/layout/component/AddressEdit.tsx
🚀 Ticket
name : 배송지주소(수정)
task : 배송지주소(수정) 레이아웃
🐝 Issue
모달에 넣으면 변경될 여지가 있으니 추후 작업이 필요할듯
=> ADD: 배송지주소 레이아웃

package-lock.json, package.json, src/Styles/GlobalStyle.ts, src/Styles/theme.ts, src/index.tsx, src/pages/ProductDetail/ProductDetail.style.ts, src/pages/ProductDetail/ProductDetail.tsx, src/pages/SignIn/SignIn.style.ts, src/pages/SignIn/SignIn.tsx
- name :  <회원가입>
- task : <회원가입> 페이지 레이아웃 구현 중
<br />
- 로고 생성 완료했습니다.
- style props를 받으니 에러 메세지를 띄울 때 변형이 일어나서(보면서 말씀드릴게요) 논의가 필요합니다. => 이 부분 확인 부탁해요!
=> [ADD] <회원가입> 페이지 레이아웃 구현 중

src/pages/Login/Login.style.ts, src/pages/Login/Login.tsx
- name :  로그인 레이아웃
- task : 레이아웃
<br />
- 유정님 회원가입 스타일과 결을 맞췄습니다. 
- 로고 버튼을 추가하였습니다.
- Input 사이 margin을 0.4rem에서 0.6rem으로 수정하였습니다. ( errorMessage 추가 시 여백 부족할듯)
=> [MODIFY] <로그인> 레이아웃 수정

src/layout/component/Header.tsx, src/layout/component/style/Footer.style.ts, src/layout/component/style/Header.style.ts
- name :  레이아웃
- task : 헤더
<br />
- 헤더 fixed를 sticky로 수정
=> MODIFY : 헤더 스타일 변경

src/pages/Payment/Payment.style.ts, src/pages/Payment/Payment.tsx
- name :  <결제> 레이아웃 구현
- task : 
🔜 배송 옵션(배송지 추가 컴포넌트 사용)
🔜 결제 수단 (101 라디오 버튼 css )
✔️ 결제 정보
<br />
-
=> [ADD] <결제> 페이지 레이아웃 구현 중

src/Router.tsx, src/pages/Payment/Payment.style.ts, src/pages/Payment/Payment.tsx
=> [MODIFY] <결제 완료> 페이지 레이아웃 수정 중

src/pages/Login/Login.style.ts, src/pages/Login/Login.tsx
- name :  로그인
- task : 로그인 레이아웃 수정사항 반영
<br />
- StyledButton의 isMargin={true}가 애매하게 짧은 것 같아(0.3rem)서, StyledButton의 바로 위의 인풋에 bottom 1rem을 줬는데, 
Common StyledInput에 '0 0 0.5rem 0' isMarginTrue에 0.5rem으로 하면 어떨삽사 합니다..
=> [MODIFY] <로그인> 수정사항 반영

public/data/cartData.json, src/pages/Cart/Cart.style.ts, src/pages/Cart/Cart.tsx
- name :  장바구니
- task : mock데이터를 삽입하여 레이아웃을 구성함
<br />
- style에서 margin과 font-size를 많이 작성하게 되었는데, 잘 한건지 혹은 더 나은 방법이 있는지 궁금합니다.!
=> [MODIFY] <장바구니> 레이아웃 수정

src/components/Address/AddressEdit.style.ts, src/components/Address/AddressEdit.tsx
- name :  배송지추가(수정)
- task : 레이아웃 수정사항 반영
<br />
- 주소검색 버튼 border-radius가 왼쪽에는 적용되지만 오른쪽에는 적용되지 않음
=> [MODIFY] <배송지추가(수정)> 레이아웃 수정사항 반영

src/pages/SignIn/SignIn.style.ts, src/pages/SignIn/SignIn.tsx
- name : <회원가입>  
- task : 피드백 수정 완료
<br />
- InputButtonGroup 태그를 ControlGroup으로 수정한 코드를 주석 처리하여 작성해두었습니다. 주석 처리를 풀고 확인 해주세요! ControlGroup에 디폴트로 지정돼있는 버튼의 border radius가 전체적인 디자인과 이질감이 있어요. 그래서 ControlGroup 적용을 하지 않았는데 방법이 있을까요?
=> [MODIFY] <회원가입> 페이지 피드백 적용 완료

src/pages/SignIn/SignIn.tsx
- name :  <회원가입>
- task : 레이아웃 완성
<br />
- 끄읏!(아마도..)
=> [MODIFY] 회원가입 레이아웃 완성

src/components/MyPage/ChangePw.tsx, src/components/MyPage/PersonalInfo.style.ts, src/components/MyPage/PersonalInfo.tsx
- name :  <마이페이지> 
task : 모달 레이아웃 구현중
<br />
- PersonalInfo.tsx 에서 배송지추가 클릭시 모달 구현했는데 클릭을 두번해야해서 한번 봐주세용..🥹 요리조리 바꿔봤는데 아예사라지거나 위치바뀌거나 막 그렇더라구요ㅠㅠ
- 그래서 해결 후에 컴포넌트로 빼주려고 합니다!
- 배송지 삭제 모달이 있는데 피그마상에서 삭제 버튼이 안보여서 어디에 하는게 좋을지 여쭙습니다!
=> [ADD] <마이페이지> 레이아웃 구현

src/Styles/theme.ts, src/pages/Payment/Payment.style.ts, src/pages/Payment/Payment.tsx
- name :  <결제> 레이아웃 피드백 적용 완료 
- task : <결제> 레이아웃 피드백 적용 중 
<br />
- 배송지 목록 정인님 component import 하고 있는데 Height 부분도 조건부 렌더링 걸어야 할 것 같앙여 !
=> [MODIFY] <결제> 레이아웃 피드백 적용 완료

src/pages/ProductList/ProductList.style.ts, src/pages/ProductList/ProductList.tsx, src/types/components.ts
- name :  <상품 목록> 페이지 레이아웃 _ * 필터링 부분
- task : <상품 목록> 페이지 레이아웃 
<br />
-
=> [ADD] <상품 목록> 페이지 레이아웃 _ * 필터링 부분 

src/pages/Cart/Cart.style.ts, src/pages/Cart/Cart.tsx
- name :  장바구니
- task : 장바구니 레이아웃
<br />
- 수정사항 피드백 반영하여 수정했습니다.
- text를 최대한 Typography에서 사용하였습니다.
- 삭제버튼 모달 추가구현하였습니다.
=> [MODIFY] <장바구니> 수정사항반영

src/Router.tsx, src/components/Address/AddressEdit.style.ts, src/components/Address/AddressEdit.tsx, src/types/components.ts
- name :  배송지수정 Address Edit
- task : 배송지수정 레이아웃
<br />
- showRecipient를 props:boolean 으로 받습니다. 수령인 Input을 선택적으로 사용할 수 있습니다.
```javascript
<AddressEdit showRecipient={false} />
```
```javascript
const AddressEdit: FC<PaymentShowRecipientProps> = ({ showRecipient }) => {
return (
{/* ... */}
{showRecipient && (
<StyledInput
margin="0 0 0.5rem 0"
label="수령인 *"
// errorMessage='수령인 이름을 입력해주세요.'
/>
)}
{/* ... */}
};
export default AddressEdit;
```
<br />
<br />
- 조건부 렌더링을 위해 타입을 추가하였습니다.
```javascript
export interface PaymentShowRecipientProps {
showRecipient: boolean;
}
```
<br />
<br />
- 배송지추가 버튼클릭시 모달에 <AddressEdit />이 구현되도록 작성
- Modal에 구현되는 <AddressEdit /> witdh를 조절하기 어려워 <AddressEdit /> 자체를 width : 80% 로 작성함
=> [MODIFY] <배송지수정> 수정사항반영

src/pages/Main/Main.tsx, src/pages/ProductList/ProductList.style.ts, src/pages/ProductList/ProductList.tsx
- name :  <상품 목록> 페이지 레이아웃 _ * 필터 박스 _ 피드백 적용 완료
- task : <상품 목록> 페이지 레이아웃 _ * 필터 박스
<br />
-
=> [MODIFY] <상품 목록>페이지 레이아웃 _ *필터 박스 _ 피드백 적용 완료

src/components/MyPage/ChangePw.style.ts, src/components/MyPage/PaymentDetail.style.ts, src/components/MyPage/PersonalInfo.style.ts, src/components/MyPage/PersonalInfo.tsx, src/pages/Main/Main.tsx, src/types/components.ts
- name : <마이페이지> 개인정보관리 배송지 목록 레이아웃
- task : 개인정보관리 배송지 목록 컴포넌트 안가져오고 코드를 가져와 스타일 수정
<br />
- 기존 컴포넌트를 사용하면 수정사항이 조금 생겨서 AddressList 코드 가져와 스타일 바꿔줬습니다! (props 로 받아오기 어려운것 같아서? 그런건데 제가 모르는 방법이 있을지도 여쭤봅니다!)
- StyledRadioButtonBox 스타일의 padding 을 삭제하고 싶은데 ..어딨는지 검색해도 안나옵니다 ㅜㅜ
```
padding: 12px 16px
```
- 삭제 버튼 클릭시 모달이 작아서 취소,확인 버튼이 안나옵니다. 이 부분도 height 값을 따로 줄 수 있는건지 여쭤봅니댜
=> [ADD] <마이페이지> 개인정보관리 배송지 목록 레이아웃

src/components/Address/AddressList.style.ts, src/components/Address/AddressList.tsx, src/types/components.ts
- name :  배송지목록
- task : 수정사항반영 및 모달 추가
<br />
- 수정사항을 반영하여 라디오버튼 컴포넌트로 대체하였습니다.
- showAddressTitle props:boolean을 추가하여 Title에 따른 조건부 렌더링을 구현하였습니다.
```javascript 
<AddressList showAddressTitle={true} /> 
```
<br />
- AddressTitleProps의 타입을 추가하였고, 이전에 작성한 타입명을 Address에서 AddressDataProps으로 변경하였습니다.
```javascript 
export interface AddressDataProps {
id: number;
name: string;
addressDetail: string;
}
export interface AddressTitleProps {
showAddressTitle: boolean;
}
```
<br />
- 배송지추가 버튼을 누르면 배송지수정 <AddressEdit />의 모달이 구현되도록 작성하였습니다.
```javascript 
<Modal
opener={
<S.StyledTextButton leftIcon={<AddIcon />}>
배송지추가
</S.StyledTextButton>
}
title="배송지 추가"
contents={<AddressEdit />}
successText="확인"
cancelText="취소"
onSuccess={() => alert('추가완료!')}
/>
```
=> [ADD] <배송지목록> 배송지수정 모달 추가

src/pages/Payment/Payment.tsx
- name :  
- task : Issues AddressList 해결 
📌 AddressList 컴포넌트의 props 정의 
<br />
-
=> [MODIFY] <결제> 레이아웃 _ AddressList props 추가!

src/components/Address/AddressEdit.style.ts, src/components/Address/AddressEdit.tsx
- name :  배송지수정
- task : 기본배송지 체크박스 추가
<br />
-
=> [ADD] <배송지수정> default address checkbox 추가

src/layout/component/Header.tsx
=> [ADD] <헤더> 버튼클릭시 이동구현

src/components/Address/AddressEdit.tsx
- name :  배송지수정
- task : checkbox 조건부렌더링 추가
<br />
-
=> [MODIFY] <배송지수정> checkbox props 추가

src/pages/Payment/Payment.tsx
- name : <결제> 레이아웃 구현중 
- task : <결제> 레이아웃 _ props 추가 
<br />
```<Modal
opener={<S.DelieveryList>배송지 목록</S.DelieveryList>}
title="배송지 추가"
contents={
<AddressList showAddressTitle={false} showContents={true} />
} //  이 부분 props 추가 완료 
successText="확인"
modalWidth="40%"
onSuccess={() => alert('선택 완료!')}
/>
```
=> [MODIFY]<결제> 레이아웃 _ props 추가 

src/Styles/common.style.ts, src/components/MyPage/ChangePw.style.ts, src/components/MyPage/ChangePw.tsx, src/components/MyPage/PaymentDetail.tsx, src/components/MyPage/PersonalInfo.style.ts, src/components/MyPage/PersonalInfo.tsx, src/components/Paid/OrderDetailComponent.tsx, src/pages/Payment/Payment.tsx, src/types/components.ts
- name : <마이페이지> 레이아웃
- task :  <마이페이지> 상세보기 모달
<br />
- 내일 질문!
=> [ADD] <마이페이지> 상세보기 모달

src/pages/ProductList/ProductList.style.ts, src/pages/ProductList/ProductList.tsx
- name :  <상품리스트> 레이아웃
- task : <상품리스트> 상품카드 레이아웃 구현
<br />
- Main.tsx 
```ts
<Slide key={`ViewAllButton-${order}`}>
{/* <PlayGroundBanner
backgroundColor={Colors[`blue${(((order - 1) % 6) + 1) * 100}`]}
>
배너{order}
</PlayGroundBanner> */}
</Slide>
```
파일에 에러가 나서 PlayGroundBanner 부분 잠시 주석처리 하겠습니다!
=> [ADD] <상품리스트> 상품카드 레이아웃 구현

public/data/orderInfo.json, src/components/Paid/OrderInfoComponent.tsx, src/pages/Payment/Payment.tsx, src/types/components.ts
=> [ADD] <결제완료> 레이아웃 구현 _ 배송중  상태 props 추가

src/components/MyPage/PaymentDetail.tsx, src/pages/Paid/Paid.tsx, src/pages/Payment/Payment.tsx, src/types/components.ts
=> [ADD] <결제 완료> 레이아웃 _  배송중 상태 props 추가

src/pages/ProductList/ProductList.style.ts, src/pages/ProductList/ProductList.tsx, src/types/components.ts
=> [MODIFY] <상품리스트> 상품카드 레이아웃  

public/data/addressList.json, src/components/Address/AddressEdit.tsx, src/components/Address/AddressList.tsx, src/types/components.ts
- name :  배송지수정
- task : 데이터 구조 수정 및 타입구조 수정 
<br />
-
=> [MODIFY] <배송지수정> 배송지 데이터 수정

src/Router.tsx, src/layout/component/Header.tsx, src/layout/component/style/Header.style.ts, src/pages/ProductList/ProductList.style.ts, src/pages/ProductList/ProductList.tsx
- name :  header
- task : header link 이동 구현
<br />
-
=> [ADD] <헤더> 페이지 이동 구현 및 카테고리 타이틀 추가

src/components/ProductCard/ProductCard.tsx, src/pages/ProductList/ProductList.tsx, src/types/components.ts
=> ADD: header Link 추가 및 item detail link 추가

src/pages/ProductDetail/ProductDetail.style.ts, src/pages/ProductDetail/ProductDetail.tsx, src/types/components.ts
=> ADD: detail 기능 구현 및 일부 수정

src/pages/ProductDetail/ProductDetail.style.ts, src/pages/ProductDetail/ProductDetail.tsx
- name : <상품 상세> 페이지 컬러, 사이즈, 장바구니 버튼
- task : 컬러, 사이즈 선택 시 버튼 스타일 변화 & 컬러, 사이즈 선택돼야만 장바구니 버튼 활성화
<br />
-
=> [ADD] <상품 상세> 컬러, 사이즈 버튼 선택 시 장바구니 버튼 활성화  

src/layout/component/Header.tsx, src/pages/Login/Login.style.ts, src/pages/Login/Login.tsx, src/types/components.ts
- name :  로그인/로그아웃 기능 구현
- task : 로그인 유효성 검사
<br />
-
=> [ADD] <로그인> 로그인/로그아웃 기능 구현

src/layout/component/Header.tsx
- name :  로그인/로그아웃 기능 구현
- task : 토큰에 따른 페이지 이동 및 헤더 레이아웃 구현
<br />
- 토큰 저장 후 기능이 작동하는지 아직 확인하지 못함
=> [ADD] <헤더> 토큰 유무에 따른 헤더 레이아웃 구현

src/pages/Login/Login.tsx
=> DELETE : axios error message

src/pages/ProductDetail/ProductDetail.tsx, src/types/components.ts
- name :  상품상세
- task : 
1. 버튼 및 사이즈 핸들링
2. 서브이지미 호버시 메인이미지 변경
3. 색상 기본 값 포커스
4. 색상 클릭 시 이미지 변경
<br />
-
=> [ADD] <상품상세> hover시 이미지 변경 추가

src/api.tsx, src/pages/ProductDetail/ProductDetail.tsx
=> ADD: implement fetch data

src/pages/Main/Main.tsx
=> [MODIFY] fetch 주소 수정

src/pages/Main/Main.tsx
- name : 메인 페이지 
- task : 배포 테스트 중
<br />
-
=> [ADD] 배포 테스트

src/components/Address/AddressList.tsx, src/types/components.ts
=> ADD : addressList

package-lock.json, package.json, src/pages/Main/Main.tsx, src/pages/ProductList/ProductAside.style.ts, src/pages/ProductList/ProductAside.tsx, src/pages/ProductList/ProductList.style.ts, src/pages/ProductList/ProductList.tsx
- name : filter & infinite scroll 기능 
- task :
<br />
- 작업 중
=> [MODIFY] filter & infinite scroll 구현 중

package-lock.json, package.json, src/pages/Main/Main.tsx, src/pages/ProductList/ProductAside.style.ts, src/pages/ProductList/ProductAside.tsx, src/pages/ProductList/ProductList.style.ts, src/pages/ProductList/ProductList.tsx
- name : develop branch  
- task : 
<br />
-
=> [ADD] 11/28 까지 진행된 기능 추가 

src/pages/Main/Main.tsx
- name :  main 페이지
- task : 
<br />
-
=> [MODIFY] 메인 수정

package-lock.json, public/data/orderDetail.json, public/data/orderInfo.json, public/data/payment.json, src/components/MyPage/PaymentDetail.tsx, src/components/Paid/OrderDetailComponent.tsx, src/components/Paid/OrderInfoComponent.tsx, src/layout/component/Header.tsx, src/pages/Paid/Paid.tsx, src/types/components.ts
=> ADD : Mypage URL 수정
